data:
  dataset_dir: "ds005574-1.0.2"

model:
  sylber_dir: "../sylber"
  sylber_checkpoint: "../sylber/weights/sylber.ckpt"
  hubet_base_model: "facebook/hubert-base-ls960"
  wav2vec_base_model: "facebook/wav2vec2-base"
  sylber_outputs: "./pickled_podcast/outputs.pkl"
