data:
  dataset_dir: "ds005574-1.0.2"

model:
  sylber_dir: "../sylber"
  sylber_checkpoint: "../sylber/weights/sylber.ckpt"
  base_model: "facebook/hubert-base-ls960"
  sylber_outputs: "./pickled_podcast/outputs.pkl"
